### ISSUE TITLE
Can I input template variables directly into the command line?

### ISSUE THREAD

**Issue by MareoRaft** [russianidiot/jinja2stdout.py.cli#1]
Let's say the file path/to/my/template is

    Hello, {{name}}!

I'm looking for a usage like

    jinja2stdout path/to/my/template name=Mark

That will output

    Hello, Mark!

This would be most convenient.  If that's not possible, can you provide an example of how I might use a conf.py to populate the arguments?

**Comment by russianidiot** [comment]
updated. use enviroment variables
